name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        run: echo "Hi this is Vinotha"
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build-app
        run: chmod +x ci/build-app.sh && ci/build-app.sh